# Generated by Django 5.2.6 on 2025-09-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_featuresection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('cc', models.CharField(max_length=10)),
                ('model_variant', models.CharField(blank=True, max_length=100)),
                ('kilometers', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=20)),
                ('owner_number', models.CharField(choices=[('1st', '1st Owner'), ('2nd', '2nd Owner'), ('3rd', '3rd Owner')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='bikes_for_sale/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
