# Generated by Django 5.2.6 on 2025-09-10 04:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_bikeforsale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('confirmation', 'Confirmation Email'), ('admin_notification', 'Admin Notification'), ('follow_up', 'Follow-up Email'), ('resolution', 'Resolution Email')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField(help_text='HTML version of the email')),
                ('body_text', models.TextField(help_text='Plain text version of the email')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_submissions', models.IntegerField(default=0)),
                ('by_reason', models.JSONField(default=dict)),
                ('by_source', models.JSONField(default=dict)),
                ('response_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the contact person', max_length=100)),
                ('email', models.EmailField(help_text='Email address for correspondence', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^[\\+]?[1-9][\\d]{0,15}$')])),
                ('reason', models.CharField(choices=[('general_enquiry', 'General Enquiry'), ('buy_bike', 'Buy a Bike'), ('sell_bike', 'Sell a Bike'), ('exchange_bike', 'Exchange a Bike'), ('rto_service', 'RTO Service'), ('others', 'Others')], help_text='Reason for contact', max_length=20)),
                ('source', models.CharField(blank=True, choices=[('google', 'Google Search'), ('social', 'Social Media'), ('friend', 'Friend/Family'), ('advertisement', 'Advertisement'), ('other', 'Other')], help_text='How they found out about us', max_length=20, null=True)),
                ('message', models.TextField(help_text='The message content', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', help_text='Current status of the inquiry', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether confirmation email was sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to handle this inquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'db_table': 'contact_submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='contact_sub_email_903821_idx'), models.Index(fields=['created_at'], name='contact_sub_created_54b02f_idx'), models.Index(fields=['status'], name='contact_sub_status_88fb2c_idx'), models.Index(fields=['reason'], name='contact_sub_reason_3bf89c_idx')],
            },
        ),
    ]
