# Generated by Django 5.2.6 on 2025-09-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_loginbackgroundimage_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='auth_images/')),
                ('is_for_login', models.BooleanField(default=False, help_text='Check if this image is for login form')),
                ('is_for_register', models.BooleanField(default=False, help_text='Check if this image is for register form')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginBackgroundImage',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
