# Generated by Django 5.2.6 on 2025-09-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0007_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderTrustSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Trusted by Riders Like You', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='riders/')),
            ],
        ),
    ]
