# Generated by Django 5.2.6 on 2025-09-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0009_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Mission', max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='about/mission/')),
            ],
        ),
    ]
