# Generated by Django 5.2.6 on 2025-09-11 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0010_missionsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Approach', max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApproachImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='approach_images/')),
                ('approach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bikes.approachsection')),
            ],
        ),
    ]
