# Generated by Django 5.2.6 on 2025-09-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0011_approachsection_approachimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('kms_driven', models.PositiveIntegerField()),
                ('owner', models.CharField(choices=[('1st Owner', '1st Owner'), ('2nd Owner', '2nd Owner'), ('3rd Owner', '3rd Owner'), ('4th Owner', '4th Owner'), ('5+ Owner', '5+ Owner')], max_length=20)),
                ('estimated_price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
