# Generated by Django 5.2.6 on 2025-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0012_motorcycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='image',
        ),
        migrations.AddField(
            model_name='bike',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
