# Generated by Django 5.2.6 on 2025-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0013_remove_bike_image_bike_slug_alter_bike_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='featuresection',
            name='image',
        ),
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(default='bikes/default.jpg', upload_to='bikes/'),
        ),
        migrations.AddField(
            model_name='bikeforsale',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='featuresection',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bikeforsale',
            name='image',
            field=models.ImageField(default='bikes_for_sale/default.jpg', upload_to='bikes_for_sale/'),
        ),
    ]
