# Generated by Django 5.2.6 on 2025-09-14 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0014_remove_bike_slug_remove_featuresection_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikeforsale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bike for Sale', 'verbose_name_plural': 'Bikes for Sale'},
        ),
        migrations.AlterField(
            model_name='bikeforsale',
            name='kilometers',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bikeforsale',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
