# Generated by Django 5.2.6 on 2025-09-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0015_alter_bikeforsale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeforsale',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
