# Generated by Django 5.2.6 on 2025-09-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0016_alter_bikeforsale_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeforsale',
            name='slug',
        ),
    ]
