# Generated by Django 5.2.6 on 2025-09-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0017_remove_bikeforsale_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikeforsale',
            options={},
        ),
        migrations.AlterField(
            model_name='bikeforsale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes_for_sale/'),
        ),
    ]
