# Generated by Django 5.2.6 on 2025-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0018_alter_bikeforsale_options_alter_bikeforsale_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bikes/'),
        ),
    ]
